const jobs = [
  {
  id: "work-experience-tronox-kzn-sands-2025-2026",
  title: "Work Experience Opportunities – Tronox KZN Sands",
  company: "Tronox KZN Sands",
  location: "Empangeni & Mtunzini, KwaZulu-Natal",
  type: "Work Integrated Learning • Internship",
  duration: "12 Months (University of Technology) or 2 Years (TVET College)",
  reportTo: "Programme Supervisors",
  datePosted: "2025-08-22T00:00:00+02:00",
  closingDate: "2025-09-03",
  applicationLink: "mailto:Recruitment.KZNSands@Tronox.com",
  reference: "N/A",
  tags: ["Mining & Metallurgy", "Chemical Engineering", "Electrical Engineering", "Mechanical Engineering", "Work Integrated Learning"],
  shortDescription: "Exceptional work experience opportunities for students in engineering and mining disciplines at Tronox KZN Sands.",
  fullDescription: "Tronox KZN Sands offers work experience opportunities for students in Electrical Engineering, Mechanical Engineering, Chemical Engineering, Mining Surveying, Instrumentation, and Mining Engineering. Programme includes hands-on practical exposure in mineral processing and mining operations."
  },
  {
  id: "unilever-yes-programme-2025-2026",
  title: "Unilever YES Programme – Future Leaders",
  company: "Unilever",
  location: "Johannesburg, Gauteng",
  type: "YES Internship • Full-time",
  duration: "12 Months",
  reportTo: "Function Supervisors",
  datePosted: "2025-08-20T00:00:00+02:00",
  closingDate: "N/A",
  applicationLink: "https://careers.unilever.com/job/south-africa/yes-programme-12-month-internship/34155/85287558224",
  reference: "N/A",
  tags: ["IT & Technology", "Industrial Engineering", "Marketing", "Supply Chain", "Human Resources", "Finance"],
  shortDescription: "12-month Youth Employment Service programme providing practical work experience across multiple business functions.",
  fullDescription: "The Unilever YES Programme offers 12-month internships across Customer Development, Marketing, Supply Chain, HR, Finance, IT, Mechanical Engineering, and other functions for South African youth."
  },
  {
  id: "junior-software-developer-broad-media-2025",
  title: "Junior Software Developer – Broad Media",
  company: "Broad Media",
  location: "Centurion, Gauteng",
  type: "Permanent • Full-time",
  duration: "Permanent",
  reportTo: "Technical Lead / Engineering Manager",
  datePosted: "2025-08-26T00:00:00+02:00",
  closingDate: "N/A",
  applicationLink: "https://broadmedia.co.za/careers/jobs/junior-software-developer/?utm_campaign=google_jobs_apply&utm_source=google_jobs_apply&utm_medium=organic#applicationForm",
  reference: "N/A",
  tags: ["Software Development", "IT & Technology", "Full Stack", "Apps"],
  shortDescription: "Develop and maintain internal systems and standalone apps across multiple platforms within a fast-paced media tech environment.",
  fullDescription: "Junior Software Developer role focusing on designing, developing, debugging, and optimizing software for internal systems and standalone applications using various technologies and platforms."
  },
  {
  id: "rock-engineering-graduate-intern-seriti-2025-2029",
  title: "Rock Engineering Graduate Internship – Seriti (2025–2029)",
  company: "Seriti",
  location: "Emalahleni, Mpumalanga",
  type: "Graduate Internship • Full-time",
  duration: "Up to 42 Months",
  reportTo: "Operational Management Team / Technical Mentor",
  datePosted: "2025-08-26T00:00:00+02:00",
  closingDate: "2025-08-26",
  applicationLink: "https://seritiza.simplify.hr/Vacancy/Apply/upjmkm",
  reference: "N/A",
  tags: ["Mining & Metallurgy", "Rock Engineering", "Geology", "Mining Engineering"],
  shortDescription: "Structured graduate internship in the mining environment with a 42-month development pathway.",
  fullDescription: "Rock Engineering Graduate Internship providing experiential learning in mining environments through structured programme with rotational opportunities and technical mentorship."
  },
  {
  id: "psg-financial-services-graduate-programme-2026",
  title: "PSG Financial Services Graduate Programme 2026",
  company: "PSG Financial Services",
  location: "The Edge, Tygerfalls, Western Cape",
  type: "Graduate Internship • Full-time",
  duration: "12 Months",
  reportTo: "Programme Manager / Assigned Mentor",
  datePosted: "2025-08-05T00:00:00+02:00",
  closingDate: "2025-11-30",
  applicationLink: "https://myfocus.psg.co.za/CareerFocus/System/Register.aspx?qs=xcTTPuANwflZov8DRxFSTHQSnQhjfh2eDcetUV91e%2Fvc%2BvzUDUpGiWad9jD42O8r4ulBRZznX%2BlHqLiQ9sMUpQiBZ0sSodeqK9MOrwJCg%2FiW2BlC%2FWCEwSAbaBweitDJ",
  reference: "N/A",
  tags: ["Finance", "Actuarial", "Software Development", "Industrial Engineering", "Electrical Engineering", "Mechanical Engineering"],
  shortDescription: "12-month graduate programme with mentorship, technical and soft skills training, and potential for permanent placement.",
  fullDescription: "PSG Graduate Programme offering on-the-job training, soft skills development, and mentorship across finance, actuarial, engineering, and IT disciplines."
  },
  {
  id: "junior-engineer-creative-leadership-solutions-pta000013-mm-1",
  title: "Junior Engineer",
  company: "Creative Leadership Solutions",
  location: "Tshwane (Pretoria), Gauteng",
  type: "Permanent • Full-time",
  duration: "Permanent",
  reportTo: "Not Specified",
  datePosted: "2025-08-26T00:00:00+02:00",
  closingDate: "N/A",
  applicationLink: "https://www.clshr.co.za/vacancies/",
  reference: "PTA000013-MM-1",
  tags: ["Industrial Engineering", "Process Engineering", "Business Analysis"],
  shortDescription: "Junior Engineer to analyse, design, and optimise business processes for a startup-focused software & marketing firm.",
  fullDescription: "Junior Engineer role focusing on business process analysis, optimization, and continuous improvement in a startup environment. Requires engineering degree and strong analytical skills."
  },
  {
  id: "graduate-engineering-internship-ann-swann-jhb002179-js",
  title: "Graduate Engineering Internship",
  company: "Ann Swann Personnel",
  location: "Johannesburg, Gauteng",
  type: "Internship • Full-time",
  duration: "Not Specified",
  reportTo: "Senior Engineers",
  datePosted: "2025-08-29T00:00:00+02:00",
  closingDate: "N/A",
  applicationLink: "N/A",
  reference: "JHB002179/JS",
  tags: ["Mechanical Engineering", "Electrical Engineering", "Industrial Engineering", "Graduate Programme"],
  shortDescription: "Kickstart your career with a Graduate Engineering Internship in Johannesburg for BEng/BSc graduates.",
  fullDescription: "Graduate Engineering Internship providing hands-on experience in mechanical, electrical, and industrial engineering disciplines with senior engineer mentorship."
  },
  {
  id: "engineering-internship-baker-hughes-r135906",
  title: "6 - 18 Weeks University Internship – Engineering Intern 2025",
  company: "Baker Hughes",
  location: "Century City, Western Cape",
  type: "Internship • Full-time",
  duration: "6–18 Weeks",
  reportTo: "Assigned Mentor/Manager",
  datePosted: "2024-11-26T00:00:00+02:00",
  closingDate: "N/A",
  applicationLink: "https://careers.bakerhughes.com/global/en/job/R135906/6-18-Weeks-University-Internship-Engineering-Intern-2025-Opportunities-Century-City?utm_campaign=google_jobs_apply&utm_source=google_jobs_apply&utm_medium=organic",
  reference: "R135906",
  tags: ["Mechanical Engineering", "Electrical Engineering", "Chemical Engineering", "Energy", "STEM"],
  shortDescription: "Global engineering internship with Baker Hughes offering hands-on experience in energy innovation.",
  fullDescription: "Baker Hughes engineering internship providing training, project experience, and mentorship in energy technology for STEM students and recent graduates."
  },
  {
  id: "wil-civil-internship-power-construction-uo8un2",
  title: "Work-Integrated Learning Opportunity: National Diploma in Civil",
  company: "Power Construction (Pty) Ltd",
  location: "Swellendam, Western Cape",
  type: "Internship • Contract",
  duration: "6 Months",
  reportTo: "Site Supervisor",
  datePosted: "2025-08-05T00:00:00+02:00",
  closingDate: "2025-08-31",
  applicationLink: "https://powergrp.simplify.hr/vacancy/uo8un2",
  reference: "N/A",
  tags: ["Civil Engineering", "Construction", "Infrastructure", "Work Integrated Learning"],
  shortDescription: "6-month WIL opportunity in Civil Engineering with Power Construction in Swellendam.",
  fullDescription: "Civil Engineering Work-Integrated Learning placement for National Diploma students needing practical experience in construction and infrastructure projects."
  },
  {
  id: "industrial-engineer-intern-restonic",
  title: "Industrial Engineer Intern – Restonic",
  company: "Restonic",
  location: "Epping, Cape Town, Western Cape",
  type: "Internship • Full-time",
  duration: "12-Month Fixed-Term",
  reportTo: "Operations Manager",
  datePosted: "2025-09-03T07:20:05+02:00",
  closingDate: "2025-09-11",
  applicationLink: "https://restonicsa.erecruit.co/candidateapp/Jobs/View/SLE250902-1?source=Indeed",
  reference: "SLE250902-1",
  tags: ["Industrial Engineering", "Manufacturing", "Process Engineering", "Work Integrated Learning"],
  shortDescription: "12-month Industrial Engineer Internship at Restonic for recent BSc Industrial Engineering graduates.",
  fullDescription: "Industrial Engineer Internship focusing on process optimization, cost management, and continuous improvement in mattress manufacturing environment."
  },
  {
  id: "technical-consulting-trainee-thales",
  title: "Technical Consulting Trainee – Shape Tomorrow's Technology Today",
  company: "Thales",
  location: "Johannesburg, Gauteng",
  type: "Trainee • Full-time",
  duration: "Not Specified",
  reportTo: "Senior Consultants",
  datePosted: "2025-09-02T16:57:12+02:00",
  closingDate: "Open until filled",
  applicationLink: "https://careers.thalesgroup.com/global/en/job/R0298159/Technical-Consulting-Trainee?utm_source",
  reference: "R0298159",
  tags: ["IT & Technology", "Software Development", "Consulting", "Smart Card Technology"],
  shortDescription: "Technical Consulting Trainee at Thales implementing smart card solutions and working with global teams.",
  fullDescription: "Technical Consulting Trainee role focusing on translating customer requirements into smart card solutions and applying industry standards in global projects."
  },
  {
  id: "industrial-engineering-trainee-national-brands",
  title: "Industrial Engineering In-service Trainee",
  company: "National Brands Limited",
  location: "Rosslyn, Pretoria, Gauteng",
  type: "Trainee • Contract",
  duration: "Not Specified",
  reportTo: "Site Industrial Engineer",
  datePosted: "2025-09-02T15:42:11+02:00",
  closingDate: "2025-09-16",
  applicationLink: "https://nationalbrandslimited.simplify.hr/vacancy/883t74?utm_source=Indeed&utm_medium=Organic&utm_campaign=organic_feed",
  reference: "N/A",
  tags: ["Industrial Engineering", "FMCG", "Manufacturing", "Process Engineering"],
  shortDescription: "Industrial Engineering In-service Trainees for National Brands Limited at Rosslyn Factory.",
  fullDescription: "Industrial Engineering traineeship focusing on process optimization, operational excellence, and quality assurance in biscuit manufacturing."
  },
  {
  id: "engineer-in-training-control-instrumentation",
  title: "Engineer In Training – Control & Instrumentation",
  company: "Lesedi Nuclear Division",
  location: "Cape Town, Western Cape",
  type: "EIT Programme • Contract",
  duration: "Not Specified",
  reportTo: "Design Group Lead",
  datePosted: "2025-09-02T06:25:34+02:00",
  closingDate: "2025-09-11",
  applicationLink: "https://lesedins.simplify.hr/vacancy/q4zhol?utm_source=Indeed&utm_medium=Organic&utm_campaign=organic_feed",
  reference: "N/A",
  tags: ["Electrical Engineering", "Instrumentation", "Nuclear", "ECSA Registration"],
  shortDescription: "Control & Instrumentation Engineer In Training at Lesedi Nuclear working toward ECSA registration.",
  fullDescription: "Engineer In Training role in Control & Instrumentation focusing on nuclear projects and professional development toward ECSA registration."
  },
  {
  id: "mechatronic-technician-intern-rheinmetall",
  title: "Mechatronic Technician Intern",
  company: "Rheinmetall Denel Munition",
  location: "Potchefstroom, North West",
  type: "Internship • Full-time",
  duration: "Not Specified",
  reportTo: "Simulation and Testing Group",
  datePosted: "2025-09-02T06:13:27+02:00",
  closingDate: "N/A",
  applicationLink: "https://www.rheinmetall.com/de/job/mechatronic_technician_intern_/821612",
  reference: "ZA00711",
  tags: ["Mechanical Engineering", "Mechatronics", "Electronics", "Defense Technology"],
  shortDescription: "Mechatronic Technician Intern at Rheinmetall Denel Munition designing custom mechatronic systems.",
  fullDescription: "Mechatronic Technician Intern role focusing on circuit fabrication, technical support, and hardware development for defense applications."
  },
  {
  id: "endpoint-security-intern-gijima",
  title: "Endpoint Security Intern",
  company: "Gijima",
  location: "Midrand, Gauteng",
  type: "Internship • Full-time",
  duration: "Not Specified",
  reportTo: "Cyber Security Team",
  datePosted: "2025-09-01T10:32:34+02:00",
  closingDate: "2025-09-04",
  applicationLink: "https://webapp.placementpartner.com/wi/vacancy/?id=gijima_youth&VacRef=JHB000150&preview=ed7c3d2ba7ecc99da1a72a5977263259",
  reference: "JHB000150",
  tags: ["IT & Technology", "Cybersecurity", "Network Security", "Endpoint Protection"],
  shortDescription: "Endpoint Security Intern for Gijima's Cyber Security team working with enterprise security tools.",
  fullDescription: "Endpoint Security Internship focusing on cybersecurity operations, threat detection, and security tool management in enterprise environment."
  },
  {
  id: "information-technology-intern-elkanah",
  title: "Information Technology Intern",
  company: "Elkanah House (ADvTECH)",
  location: "Sunningdale, Western Cape",
  type: "Internship • Contract",
  duration: "Not Specified",
  reportTo: "IT Team",
  datePosted: "2025-09-01T09:54:05+02:00",
  closingDate: "2025-09-05",
  applicationLink: "https://elkanahhouse.simplify.hr/vacancy/xe4zpa?utm_source=Indeed&utm_medium=Organic&utm_campaign=organic_feed",
  reference: "N/A",
  tags: ["IT & Technology", "Software Development", "Education Technology", "Technical Support"],
  shortDescription: "IT Intern at Elkanah House assisting with software projects and technical support.",
  fullDescription: "IT Internship role focusing on software development, technical research, and user support in educational technology environment."
  },
  {
  id: "healthcare-technology-trainee-siemens",
  title: "Junior Customer Service Engineer Software Trainee",
  company: "Siemens Healthineers",
  location: "Midrand, Gauteng",
  type: "Fixed Term • Full-time",
  duration: "Not Specified",
  reportTo: "Varian Business Unit",
  datePosted: "2025-09-01T06:29:53+02:00",
  closingDate: "N/A",
  applicationLink: "https://jobs.siemens.com/careers/job/563156127141230?hl=en&utm_source=indeed&domain=siemens.com",
  reference: "N/A",
  tags: ["Electrical Engineering", "Electronics", "Healthcare", "Medical Technology", "Y.E.S. Programme"],
  shortDescription: "Healthcare Technology Trainee at Siemens Healthineers in medical equipment maintenance.",
  fullDescription: "Healthcare Technology Trainee role focusing on installation, maintenance, and customer support for medical equipment in Y.E.S. programme."
  },
  {
  id: "junior-project-engineer-pumpab-centurion",
  title: "Junior Project Engineer",
  company: "Pumpab",
  location: "Centurion, Gauteng",
  type: "Full-time • Entry Level",
  duration: "Permanent",
  reportTo: "International Project Engineer",
  datePosted: "2025-09-04T00:00:00+02:00",
  closingDate: "N/A",
  applicationLink: "mailto:geo@pumpab.co.za",
  reference: "N/A",
  tags: ["Mechanical Engineering", "Chemical Engineering", "Project Management", "Pump Systems"],
  shortDescription: "Junior Project Engineer supporting international projects for Australian branch.",
  fullDescription: "Junior Project Engineer role focusing on proposal drafting, project execution support, and application engineering for pump systems. Email applications to geo@pumpab.co.za"
  },
  {
  id: "electrical-mechanical-engineer-learnership-oneconnect",
  title: "Electrical/Mechanical Engineer Learnership",
  company: "Oneconnect",
  location: "JHB - Eastern Suburbs, Gauteng",
  type: "Learnership • Full-time",
  duration: "Not Specified",
  reportTo: "N/A",
  datePosted: "2025-08-25T00:00:00+02:00",
  closingDate: "N/A",
  applicationLink: "https://webapp.placementpartner.com/wi/application_form.php?id=oneconnect_solutions&vacancy_ref=JHB000122-Admin-1&source=pnet",
  reference: "JHB000122-Admin-1",
  tags: ["Electrical Engineering", "Mechanical Engineering", "Learnership", "Masters Graduates"],
  shortDescription: "Structured Learnership Program for Master's graduates in Electrical or Mechanical Engineering.",
  fullDescription: "Learnership programme for Master's graduates in Electrical/Mechanical Engineering bridging academia and industry with practical experience."
  },
  {
  id: "graduate-programme-2026-ey",
  title: "Graduate Programme 2026",
  company: "Ernst & Young (EY) South Africa",
  location: "Johannesburg, Gauteng; Bloemfontein, Free State; Cape Town, Western Cape",
  type: "Graduate Programme • Full-time",
  duration: "Not Specified",
  reportTo: "N/A",
  datePosted: "2025-09-07T00:00:00+02:00",
  closingDate: "Not Specified",
  applicationLink: "https://www.gilejobs.co.za/internship/ernst-young-ey-south-africa-graduate-programme-2026/",
  reference: "N/A",
  tags: ["Finance", "IT & Technology", "Industrial Engineering", "Software Development", "Cybersecurity", "Tax", "Accounting"],
  shortDescription: "Multiple graduate opportunities across Strategy, Digital Risk, Supply Chain, Tax, and Assurance.",
  fullDescription: "EY Graduate Programme 2026 offering opportunities in Strategy & Transactions, Digital Risk, Supply Chain, FAAS Regulatory, Tax, and Assurance for various disciplines."
  },
  {
  id: "engineering-graduates-network-engineering-centurion",
  title: "Engineering Graduates",
  company: "Network Engineering",
  location: "Centurion, Gauteng",
  type: "Permanent • Full-time",
  duration: "Permanent",
  reportTo: "N/A",
  datePosted: "2025-09-03T00:00:00+02:00",
  closingDate: "N/A",
  applicationLink: "https://webapp.placementpartner.com/wi/application_form.php?id=network2&vacancy_ref=NES022602-SV-1&source=pnet",
  reference: "NES022602-SV-1",
  tags: ["Electrical Engineering", "Electronic Engineering", "Mechatronic Engineering", "Cutting-edge Technology"],
  shortDescription: "Opportunity for Electronic and Mechatronic Graduates to work with state-of-the-art systems.",
  fullDescription: "Engineering graduate positions for Electronic and Mechatronic engineers to work with advanced electronic and mechatronic systems in technology environment."
  },
  {
  id: "graduate-electrical-engineer-network-finance-jhb-north",
  title: "Graduate Electrical Engineer",
  company: "Network Finance",
  location: "Johannesburg North, Gauteng",
  type: "Permanent • Full-time",
  duration: "Permanent",
  reportTo: "N/A",
  datePosted: "2025-09-08T00:00:00+02:00",
  closingDate: "N/A",
  applicationLink: "https://www.jobmail.co.za/jobs/management/general-management/johannesburg-north/graduate-electrical-engineer-id-7319032",
  reference: "NES022827/KSE",
  tags: ["Electrical Engineering", "Graduate Programme", "Project Engineering", "Design"],
  shortDescription: "Graduate role assisting with design, development, and testing of electrical systems.",
  fullDescription: "Graduate Electrical Engineer role focusing on technical drawings, calculations, site visits, and electrical system design in project environment."
  },
  {
  id: "graduate-software-developers-shape-the-future-of-ai-driven-enterprise-solutions",
  title: "Graduate Software Developers – Shape the Future of AI-Driven Enterprise Solutions",
  company: "Leading Technology Solutions Provider",
  location: "Pretoria, Gauteng",
  type: "Permanent • Full-time",
  duration: "Permanent",
  reportTo: "Programme Supervisors",
  datePosted: "2025-09-08T06:49:28+02:00",
  closingDate: "2025-09-11",
  applicationLink: "https://jobs.recruit360.co.za/jobs/graduate-software-developers?source=indeed",
  reference: "N/A",
  tags: ["Software Development", "AI", "Machine Learning", "C#", ".NET", "AWS"],
  shortDescription: "Join our team developing cutting-edge AI solutions for modern enterprises.",
  fullDescription: "Graduate Software Developer role focusing on AI-driven enterprise solutions using C#/.NET and AWS cloud technologies. Requires strong mathematical background."
  },
  {
  id: "instrumentation-technician-intern-rheinmetall-denel-munition-rf-pty-ltd-potchefstroom",
  title: "Instrumentation Technician Intern",
  company: "Rheinmetall Denel Munition",
  location: "Potchefstroom, North West",
  type: "Internship • Full-time",
  duration: "Not Specified",
  reportTo: "Programme Supervisors",
  datePosted: "2025-09-08T05:42:01+02:00",
  closingDate: "N/A",
  applicationLink: "https://www.rheinmetall.com/de/job/instrumentation_technician_intern/680800",
  reference: "ZA00555",
  tags: ["Electrical Engineering", "Instrumentation", "PLC", "Industrial Instrumentation"],
  shortDescription: "Instrumentation Technician Intern maintaining instruments and performing calibrations.",
  fullDescription: "Instrumentation Technician Intern role focusing on instrument maintenance, calibration, technical drawing interpretation, and PLC programming."
  },
  {
  id: "launch-your-engineering-career-with-schneider-electric-s-2026-graduate-trainee-program",
  title: "Schneider Electric's 2026 Graduate Trainee Program",
  company: "Schneider Electric",
  location: "South Africa (Hybrid)",
  type: "Graduate Programme • Full-time",
  duration: "24-Month Program",
  reportTo: "Programme Supervisors",
  datePosted: "2025-09-05T10:24:33+02:00",
  closingDate: "N/A",
  applicationLink: "https://careers.se.com/global/jobs/97235?lang=en-us&previousLocale=en-US",
  reference: "N/A",
  tags: ["Electrical Engineering", "Mechatronics", "Computer Engineering", "STEM", "Electrification", "Automation"],
  shortDescription: "24-month graduate program with hands-on experience and guaranteed permanent placement.",
  fullDescription: "Schneider Electric Graduate Trainee Program offering 24-month development with mentorship, international opportunities, and permanent placement for STEM graduates."
  },
  {
  id: "software-engineering-graduate-program-betway-jackpot-city",
  title: "Software Engineering Graduate Program",
  company: "Betway/Jackpot City",
  location: "Johannesburg & Cape Town",
  type: "Graduate Program • Full-time",
  duration: "Not Specified",
  reportTo: "Programme Supervisors",
  datePosted: "2025-09-05T09:53:15+02:00",
  closingDate: "2025-09-30",
  applicationLink: "https://supergroupgraduates.com/southafrica#reg",
  reference: "N/A",
  tags: ["Software Development", "iGaming", "C#", "SQL", "JavaScript", "Angular"],
  shortDescription: "Software Engineering Graduate Program in sports betting and iGaming industry.",
  fullDescription: "Software Engineering Graduate Program focusing on C#, SQL Server, JavaScript, and Angular development in sports betting and iGaming environment."
  },
  {
  id: "it-administrator-officer-learner-momentum-life",
  title: "IT Administrator Officer Learner",
  company: "Momentum Life",
  location: "Centurion, Gauteng",
  type: "Temporary • Full-time",
  duration: "Not Specified",
  reportTo: "Programme Supervisors",
  datePosted: "2025-09-04T08:02:55+02:00",
  closingDate: "2025-09-05",
  applicationLink: "https://momentumgroupltd.internal.erecruit.co/candidateapp/Jobs/View/MMH250826-4?utm_source=Indeed&utm_medium=organic&utm_campaign=Indeed",
  reference: "MMH250826-4",
  tags: ["IT & Technology", "Administration", "Asset Management", "Technical Support"],
  shortDescription: "Entry-level IT administrative support role managing schedules and asset inventories.",
  fullDescription: "IT Administrator Officer Learner role focusing on IT administration, asset management, user support, and documentation with remote work options."
  },
  {
  id: "mining-career-internships-p1p2-harmony-gold-2025",
  title: "Internship and P1/P2 Opportunities 2025",
  company: "Harmony Gold Mining Company",
  location: "Multiple Operations (Gauteng, Free State, North West)",
  type: "Internship • P1/P2 Experiential Learning",
  duration: "2025 Program",
  reportTo: "N/A",
  datePosted: "2025-09-09T00:00:00+02:00",
  closingDate: "2024-09-27",
  applicationLink: "mailto:Interns.WE@Harmony.co.za",
  reference: "N/A",
  tags: ["Mining & Metallurgy", "Mining Engineering", "Geology", "Metallurgy", "Rock Engineering", "Environmental Management"],
  shortDescription: "Harmony Gold offers 2025 Internship and P1/P2 opportunities across multiple mining operations.",
  fullDescription: "Harmony Gold internship and experiential learning opportunities in Mining Engineering, Geology, Metallurgy, and related disciplines across various mining operations."
  },
  {
  id: "engineering-graduate-business-development-gsi-centurion",
  title: "Engineering Graduate - Business Development",
  company: "GSI Talent Solutions Pty Ltd",
  location: "Centurion, Gauteng",
  type: "Permanent • Full-time",
  duration: "Permanent",
  reportTo: "N/A",
  datePosted: "2025-09-03T00:00:00+02:00",
  closingDate: "N/A",
  applicationLink: "https://www.pnet.co.za/jobs--Engineering-Graduate-Centurion-GSI-Talent-Solutions-Pty-Ltd--4038175-inline.html",
  reference: "N/A",
  tags: ["Mechanical Engineering", "Electrical Engineering", "Aeronautical", "Business Development", "Defense Industry"],
  shortDescription: "Unique graduate role blending engineering knowledge with business development in defense industry.",
  fullDescription: "Engineering Graduate role combining technical knowledge with business development in international defense industry, requiring engineering degree and international travel readiness."
  },
  {
  id: "graduate-internship-programme-electro-mechanical-ar-engineering-2025",
  title: "Graduate Internship Programme 2025/2026",
  company: "A & R Engineering Group",
  location: "Potchefstroom, North West",
  type: "Internship • Full-time",
  duration: "18 Months",
  reportTo: "N/A",
  datePosted: "2025-09-11T00:00:00+02:00",
  closingDate: "2025-09-12",
  applicationLink: "mailto:hr@areng.co.za",
  reference: "N/A",
  tags: ["Electrical Engineering", "Mechanical Engineering", "Instrumentation", "Mining Industry", "Electro-Mechanical"],
  shortDescription: "18-month graduate internship in Electro-Mechanical Engineering and Instrumentation for mining industry.",
  fullDescription: "18-month internship programme for Electro-Mechanical Engineering and Instrumentation graduates in mining sector with monthly allowance and benefits."
  },
  {
  id: "business-analyst-graduate-shape-africa-s-financial-future",
  title: "Business Analyst Graduate",
  company: "Absa Group",
  location: "Johannesburg (Hybrid)",
  type: "Graduate Program • Full-time",
  duration: "Not Specified",
  reportTo: "Programme Supervisors",
  datePosted: "2025-09-12T06:43:53+02:00",
  closingDate: "2025-09-26",
  applicationLink: "https://absa.wd3.myworkdayjobs.com/en-US/ABSAcareersite/job/Johannesburg/Business-Analyst-Graduate_R-15979452",
  reference: "R-15979452",
  tags: ["IT & Technology", "Business Analysis", "Finance", "Banking", "Digital Transformation"],
  shortDescription: "Business Analyst Graduate role shaping Africa's financial future through digital transformation.",
  fullDescription: "Business Analyst Graduate position focusing on requirements gathering, process analysis, and stakeholder collaboration in banking digital transformation."
  },
  {
  id: "graduate-project-engineer-launch-your-engineering-career-at-cape-town-harbour",
  title: "Graduate Project Engineer",
  company: "3C Metal Group - Cinco Engineering",
  location: "Cape Town Harbour, Western Cape",
  type: "Permanent • Full-time",
  duration: "Permanent",
  reportTo: "Programme Supervisors",
  datePosted: "2025-09-12T03:29:03+02:00",
  closingDate: "N/A",
  applicationLink: "https://3cmetal-career.talent-soft.com/job/job-graduate-project-engineer_292.aspx",
  reference: "2025-292",
  tags: ["Mechanical Engineering", "Maritime", "Project Engineering", "Steel Fabrication"],
  shortDescription: "Graduate Project Engineer role at Cape Town Harbour working on maritime engineering projects.",
  fullDescription: "Graduate Project Engineer position working on steel fabrication, industrial piping, and ship repair projects in maritime industry."
  },
  {
  id: "transport-intern-launch-your-career-in-energy-logistics",
  title: "Transport Intern - Energy Logistics",
  company: "TotalEnergies",
  location: "Johannesburg, Gauteng",
  type: "Internship • Full-time",
  duration: "Not Specified",
  reportTo: "Programme Supervisors",
  datePosted: "2025-09-10T10:30:12+02:00",
  closingDate: "N/A",
  applicationLink: "https://jobs.totalenergies.com/en_US/careers/JobDetail/Transport-Internship/70506?Codes=9999#",
  reference: "N/A",
  tags: ["Industrial Engineering", "Logistics", "Supply Chain", "Energy", "Transport"],
  shortDescription: "Transport Intern at TotalEnergies gaining experience in energy logistics operations.",
  fullDescription: "Transport Internship focusing on vehicle compliance, load scheduling, and transport operations management in energy sector."
  },
  {
  id: "graduate-junior-mechanical-engineer-pretoria-jenrec",
  title: "Graduate/Junior Mechanical Engineer",
  company: "Not Specified (via JenRec Recruitment)",
  location: "Pretoria, Gauteng",
  type: "Full-time • Graduate/Junior Level",
  duration: "Not Specified",
  reportTo: "Senior Engineers",
  datePosted: "2025-09-12T00:00:00+02:00",
  closingDate: "N/A",
  applicationLink: "mailto:recruitment@jenrec.com",
  reference: "N/A",
  tags: ["Mechanical Engineering", "Mechatronics", "R&D", "Design", "Prototype Development"],
  shortDescription: "Graduate/Junior Mechanical Engineer role in Pretoria working on R&D and prototype development.",
  fullDescription: "Graduate/Junior Mechanical Engineer position focusing on mechanical design, calculations, simulations, and prototype development with multidisciplinary teams."
  },
  {
  id: "mining-engineering-internship-hlogirati-24month",
  title: "Mining Engineering Internship",
  company: "Hlogirati (Pty) Ltd",
  location: "New Clydesdale Colliery Area",
  type: "Internship • Full-time",
  duration: "24 Months",
  reportTo: "N/A",
  datePosted: "2025-09-16T00:00:00+02:00",
  closingDate: "2025-09-19",
  applicationLink: "mailto:hr@hlogirati.com",
  reference: "N/A",
  tags: ["Mining & Metallurgy", "Mining Engineering", "Mechanical Engineering", "Metallurgical Engineering"],
  shortDescription: "24-month internship program in Mining, Mechanical or Metallurgical Engineering.",
  fullDescription: "24-month mining engineering internship programme for graduates in mining, mechanical, or metallurgical engineering near New Clydesdale Colliery."
  },
  {
  id: "in-service-training-programme-cef-2025",
  title: "In-Service Training Programme 2025/2026",
  company: "CEF Group",
  location: "Sandton & SANPC Refinery",
  type: "In-Service Training • Full-time",
  duration: "Not Specified",
  reportTo: "N/A",
  datePosted: "2025-09-16T00:00:00+02:00",
  closingDate: "N/A",
  applicationLink: "N/A",
  reference: "N/A",
  tags: ["Chemical Engineering", "Civil Engineering", "Electrical Engineering", "Management", "In-Service Training"],
  shortDescription: "10 in-service training opportunities at CEF Group for N6 qualified students.",
  fullDescription: "In-service training opportunities for N6 students in engineering, management, and finance disciplines at CEF Group locations."
  },
  {
  id: "mechanical-electrical-engineers-in-training-mc-design",
  title: "Mechanical & Electrical Engineers in Training",
  company: "MC Design & Contracting",
  location: "Port Elizabeth, Eastern Cape",
  type: "Graduate Programme • Full-time",
  duration: "Not Specified",
  reportTo: "Engineering Team",
  datePosted: "2025-09-20T00:00:00+02:00",
  closingDate: "2025-10-03",
  applicationLink: "mailto:recruitment@modesign.co.za",
  reference: "N/A",
  tags: ["Mechanical Engineering", "Electrical Engineering", "EIT", "Graduate Programme"],
  shortDescription: "Graduate Engineer positions for Mechanical and Electrical Engineers at MC Design & Contracting.",
  fullDescription: "Engineer in Training positions for Mechanical and Electrical Engineering graduates seeking hands-on experience in engineering team environment."
  },
  {
  id: "fire-safety-technician-electrical-wrees",
  title: "Fire Safety Technician (Electrical)",
  company: "WREES",
  location: "Not Specified",
  type: "Full-time • Entry Level",
  duration: "Not Specified",
  reportTo: "N/A",
  datePosted: "2025-09-20T00:00:00+02:00",
  closingDate: "N/A",
  applicationLink: "mailto:hr@wrees.co.za",
  reference: "N/A",
  tags: ["Electrical Engineering", "Fire Safety", "Technician", "Maintenance"],
  shortDescription: "Fire Safety Technician role for Electrical Engineering N6 graduates inspecting safety equipment.",
  fullDescription: "Fire Safety Technician position requiring N6 Electrical Engineering qualification, focusing on inspection, testing, and maintenance of fire safety systems."
  },
  {
  id: "electrical-engineer-in-training-actom-x3",
  title: "Electrical Engineer in Training (x3)",
  company: "ACTOM (Pty) Ltd",
  location: "Redfordview, Johannesburg, Gauteng",
  type: "Graduate Programme • Full-time",
  duration: "Not Specified",
  reportTo: "N/A",
  datePosted: "2025-09-20T00:00:00+02:00",
  closingDate: "2025-09-25",
  applicationLink: "mailto:hr@actom.co.za",
  reference: "N/A",
  tags: ["Electrical Engineering", "EIT", "ECSA", "Graduate Programme"],
  shortDescription: "Three Electrical Engineer in Training positions at ACTOM working toward ECSA registration.",
  fullDescription: "Electrical Engineer in Training positions focusing on project assessment, CAD software, customer liaison, and professional development toward ECSA registration."
  },
  {
  id: "graduate-mechanical-engineer-3d-scanning-dimensional-analysis",
  title: "Graduate Mechanical Engineer - 3D Scanning & Dimensional Analysis",
  company: "Weir Minerals",
  location: "Port Elizabeth, Eastern Cape",
  type: "Graduate Programme • Full-time",
  duration: "Not Specified",
  reportTo: "N/A",
  datePosted: "2025-09-19T08:36:33+02:00",
  closingDate: "2025-09-25",
  applicationLink: "https://weir.wd3.myworkdayjobs.com/en-US/Weir_External_Careers/job/Port-Elizabeth/Graduate--Mechanical-Engineer_R0033358",
  reference: "R0033358",
  tags: ["Mechanical Engineering", "3D Scanning", "Mining", "Dimensional Analysis"],
  shortDescription: "Graduate Mechanical Engineer role specializing in 3D scanning technology at Weir Minerals.",
  fullDescription: "Graduate Mechanical Engineer position focusing on 3D scanning and dimensional analysis using Romer Absolute Arm and PolyWorks software in mining solutions."
  },
  {
  id: "it-intern-opportunities-resort-technology-division-the-beekman-group-port-shepstone-kwazulu-natal",
  title: "IT Intern - Resort Technology",
  company: "The Beekman Group",
  location: "Port Shepstone, KwaZulu-Natal",
  type: "Internship • Full-time",
  duration: "Not Specified",
  reportTo: "N/A",
  datePosted: "2025-09-18T03:27:26+02:00",
  closingDate: "N/A",
  applicationLink: "https://www.beekmangroup.com/job/3-x-it-intern-resorts/",
  reference: "36/09",
  tags: ["IT & Technology", "Hospitality", "Technical Support", "Network Systems"],
  shortDescription: "Three IT Intern positions at Beekman Group's resort operations.",
  fullDescription: "IT Intern positions focusing on hardware installation, server maintenance, network systems, and technical support in hospitality environment."
  },
  {
  id: "intern-developer-goldman-tech-johannesburg",
  title: "Intern Developer",
  company: "Goldman Tech",
  location: "Johannesburg, Gauteng",
  type: "Internship • Full-time",
  duration: "Not Specified",
  reportTo: "N/A",
  datePosted: "2025-09-20T00:00:00+02:00",
  closingDate: "N/A",
  applicationLink: "mailto:it.careers@goldmantech.co.za",
  reference: "Interndev2021",
  tags: ["Software Development", "Web Development", "Python", "PHP", "HTML5"],
  shortDescription: "Intern Developer role at Goldman Tech requiring IT degree and web development skills.",
  fullDescription: "Intern Developer position requiring IT-related degree and skills in Python/PHP, web technologies, HTML5, and CSS for development projects."
  },
  {
  id: "mechanical-draughtsman-namaqua-engineering-vredendal",
  title: "Mechanical Draughtsman",
  company: "Namaqua Engineering",
  location: "Vredendal, West Coast",
  type: "Permanent • Full-time",
  duration: "Permanent",
  reportTo: "Head of Projects",
  datePosted: "2025-09-22T00:00:00+02:00",
  closingDate: "2025-09-26",
  applicationLink: "mailto:berlus@namaqua-eng.co.za",
  reference: "N/A",
  tags: ["Mechanical Engineering", "Draughting", "SolidWorks", "Mining", "Construction"],
  shortDescription: "Mechanical Draughtsman role creating 3D models and technical drawings for mining/construction.",
  fullDescription: "Mechanical Draughtsman position requiring SolidWorks proficiency for 3D modeling, technical drawings, and BOM creation in mining and construction industry."
  },
  {
  id: "process-industrial-engineer-graduates-makhawini-recruitment",
  title: "Process/Industrial Engineer Graduates",
  company: "Makhawini Recruitment",
  location: "Not Specified",
  type: "Full-time • Graduate",
  duration: "Not Specified",
  reportTo: "N/A",
  datePosted: "2025-09-22T00:00:00+02:00",
  closingDate: "N/A",
  applicationLink: "mailto:recruitment@makhawinirecruitment.co.za",
  reference: "N/A",
  tags: ["Industrial Engineering", "Process Engineering", "Mechanical Engineering", "Graduate Programme"],
  shortDescription: "Graduate Mechanical Engineers needed for Process Engineer and Industrial Engineer roles.",
  fullDescription: "Graduate positions for Mechanical Engineering graduates seeking roles in process engineering and industrial engineering fields."
  },
  {
  id: "engineering-learnership-programme-atns-2026-2027",
  title: "Engineering Learnership Programme 2026-2027",
  company: "ATNS (Air Traffic and Navigation Services)",
  location: "Johannesburg (Bonaero Park), Gauteng",
  type: "Learnership • Full-time",
  duration: "24 Months",
  reportTo: "N/A",
  datePosted: "2025-09-22T00:00:00+02:00",
  closingDate: "2025-09-25",
  applicationLink: "https://atns.cl.br/",
  reference: "N/A",
  tags: ["Electrical Engineering", "Electronics", "Aviation", "Learnership"],
  shortDescription: "24-month Engineering Learnership for Electrical/Electronics Engineering students at ATNS.",
  fullDescription: "Engineering Learnership Programme for Electrical/Electronics Engineering students with aviation training academy and operational exposure."
  },
  {
  id: "civil-engineering-intern-mine-rehabilitation-mintek",
  title: "Civil Engineering Intern - Mine Rehabilitation",
  company: "Mintek",
  location: "Randburg, Gauteng",
  type: "Internship • Full-time",
  duration: "2025/2026 Programme",
  reportTo: "N/A",
  datePosted: "2025-09-22T00:00:00+02:00",
  closingDate: "2025-09-25",
  applicationLink: "https://mintek.ci.hr/applicant/index.php?controller=Listings&method=view&listingid=afdab9a4-d448-4fcc-b246-2f8dab95a546",
  reference: "minte_000359",
  tags: ["Civil Engineering", "Mining", "Rehabilitation", "Environmental"],
  shortDescription: "Civil Engineering internship at Mintek focusing on mine rehabilitation projects.",
  fullDescription: "Civil Engineering internship focusing on mine rehabilitation programme, site monitoring, and technical investigations in mining environment."
  },
  {
  id: "engineer-in-training-industrial-engineering-eskom",
  title: "Engineer in Training - Industrial Engineering",
  company: "Eskom",
  location: "Sunninghill, Gauteng (Megawatt Park)",
  type: "Internship • Full-time",
  duration: "Not Specified",
  reportTo: "N/A",
  datePosted: "2025-09-22T14:01:05+02:00",
  closingDate: "2025-09-30",
  applicationLink: "https://eskomcareers.ci.hr/applicant/index.php?controller=Listings&method=view&listingid=62e21f1f-41c3-4a08-88bf-51ffb05b9c89",
  reference: "N/A",
  tags: ["Industrial Engineering", "Energy", "Power Utility", "Graduate Programme"],
  shortDescription: "Engineer in Training positions at Eskom for Industrial Engineering graduates.",
  fullDescription: "Engineer in Training positions for Industrial Engineering graduates in Eskom's comprehensive development program across power utility operations."
  },
  {
  id: "fintech-internship-programme-2026-mtn",
  title: "Fintech Internship Programme 2026",
  company: "MTN",
  location: "South Africa (Remote/On-site)",
  type: "Internship • Full-time",
  duration: "2026 Programme",
  reportTo: "N/A",
  datePosted: "2025-09-22T13:37:36+02:00",
  closingDate: "2025-09-22",
  applicationLink: "https://leap.ly/opportunities/927",
  reference: "N/A",
  tags: ["IT & Technology", "Fintech", "Finance", "Digital Payments"],
  shortDescription: "MTN Fintech Internship Programme 2026 for graduates in IT, Engineering, and Finance.",
  fullDescription: "MTN Fintech Internship Programme offering hands-on experience in digital payments, mobile money, and product innovation for various graduate disciplines."
  },
  {
  id: "engineering-learnership-programme-aviation-atns",
  title: "Engineering Learnership Programme - Aviation",
  company: "ATNS (Air Traffic and Navigation Services)",
  location: "Johannesburg (Bonaero Park), Gauteng",
  type: "Learnership • Full-time",
  duration: "24 Months",
  reportTo: "N/A",
  datePosted: "2025-09-21T14:25:24+02:00",
  closingDate: "2025-09-30",
  applicationLink: "https://atns.ci.hr/applicant/index.php?controller=Listings&method=view&listingid=74437f99-995c-47e2-b770-a95fd538a55c",
  reference: "atns_000732",
  tags: ["Electrical Engineering", "Electronics", "Aviation", "Learnership"],
  shortDescription: "24-month Engineering Learnership Programme at ATNS for aviation industry.",
  fullDescription: "Engineering Learnership Programme for Electrical/Electronics Engineering graduates in aviation industry with potential permanent placement."
  },
  {
  id: "facilities-intern-engineering-momentum",
  title: "Facilities Intern - Engineering",
  company: "Momentum Group",
  location: "Bellville, Western Cape",
  type: "Internship • Temporary",
  duration: "Not Specified",
  reportTo: "N/A",
  datePosted: "2025-09-20T12:34:06+02:00",
  closingDate: "2025-09-30",
  applicationLink: "https://momentumgroupltd.internal.erecruit.co/candidateapp/Jobs/View/MMH250210-9?utm_source=Indeed&utm_medium=organic&utm_campaign=Indeed",
  reference: "MMH250210-9",
  tags: ["Electrical Engineering", "Mechanical Engineering", "Facilities Management", "HVAC"],
  shortDescription: "Facilities Intern at Momentum Group for Engineering graduates.",
  fullDescription: "Facilities Intern position for Engineering graduates focusing on electrical, mechanical, and HVAC systems maintenance in facilities management."
  },
  {
    id: "engineer-in-training-industrial-engineering-eskom-2025",
    title: "Engineer in Training - Industrial Engineering",
    company: "Eskom",
    location: "Sunninghill, Gauteng",
    type: "Internship • Full-time",
    duration: "Not Specified",
    reportTo: "N/A",
    datePosted: "2025-09-25T00:00:00+02:00",
    closingDate: "2025-09-30",
    applicationLink: "https://eskomcareers.ci.hr/applicant/index.php?controller=Listings&method=view&listingid=62e21f1f-41c3-4a08-88bf-51ffb05b9c89",
    reference: "eskom_000025",
    tags: ["Industrial Engineering", "Energy", "Power Utility", "Graduate Programme"],
    shortDescription: "Engineer in Training positions at Eskom for Industrial Engineering graduates with institutionalised and on-job training.",
    fullDescription: "Two Engineer in Training positions at Eskom's Megawatt Park for recent BEng/BSc Industrial Engineering graduates. The programme offers comprehensive institutionalised training combined with practical on-job experience across Eskom's operations divisions. Focuses on professional development in electricity and energy supply sector."
    },
    {
      id: "graduate-civil-engineer-highways-rail-wsp-2026",
      title: "2026 Graduate Civil Engineer: Highways and Rail",
      company: "WSP",
      location: "Midrand, Gauteng and Cape Town, Western Cape",
      type: "Graduate Programme • Full-time",
      duration: "Not Specified",
      reportTo: "N/A",
      datePosted: "2025-09-17T13:10:00+02:00",
      closingDate: "N/A",
      applicationLink: "https://emit.fa.ca3.oraclecloud.com/hcmUI/CandidateExperience/en/sites/CX_2001/job/73476",
      reference: "73476",
      tags: ["Civil Engineering", "Transport Infrastructure", "Highways", "Rail", "BIM", "Graduate Programme"],
      shortDescription: "Graduate Civil Engineer opportunity in Highways and Rail teams at WSP, offering exposure to transport infrastructure projects with modern BIM workflows.",
      fullDescription: "WSP is seeking Graduate Civil Engineers to join their Highways and Rail teams in Midrand or Cape Town. The role involves working on pavement design, geometric road layouts, rail systems, and traffic engineering using Revit, Civil 3D and other digital tools. Successful candidates will contribute to multidisciplinary transport infrastructure projects in a collaborative environment that values innovation and technical excellence."
      },
      
      {
        id: "desktop-support-engineer-fsca-2025",
        title: "Desktop Support Engineer – FSCA",
        company: "Financial Sector Conduct Authority (FSCA)",
        location: "Not Specified",
        type: "Permanent • Full-time",
        duration: "Permanent",
        reportTo: "Infrastructure Manager",
        datePosted: "2025-09-26T00:00:00+02:00",
        closingDate: "2025-10-03",
        applicationLink: "https://fsca.mcidirecthire.com/External/Application?Ref=KntmzAItXvLSHhGyIASaUzlhazSNGaXlRUJZLeFn8RNu4K5OWcQjG%2fmqT%2fO4PeCL8VNzVKKSyE1TvK7eBpZRLg%3d%3d",
        reference: "N/A",
        tags: ["IT & Technology", "Desktop Support", "Technical Support", "Service Desk", "Financial Services"],
        shortDescription: "Desktop Support Engineer to provide first-line IT support, manage service desk operations, and ensure seamless business operations for FSCA.",
        fullDescription: "The Financial Sector Conduct Authority seeks a Desktop Support Engineer to serve as the first point of contact for IT services. Responsibilities include managing the service desk, incident management, technical troubleshooting, system configuration, user administration, equipment management, and security implementation. Requires IT diploma, A+/N+ certification, and 1-2 years desktop support experience."
        },

        {
          id: "applications-engineer-technical-sales-pabt-centurion",
          title: "Applications Engineer – Technical Sales",
          company: "Pump and Abrasion Technologies (PABT)",
          location: "Centurion, Gauteng",
          type: "Permanent • Full-time",
          duration: "Permanent",
          reportTo: "Sales Team/Technical Manager",
          datePosted: "2025-09-25T00:00:00+02:00",
          closingDate: "N/A",
          applicationLink: "https://pabtglobal.simplify.hr/vacancy/km3xq8?utm_source=Indeed&utm_medium=Organic&utm_campaign=organic_feed",
          reference: "N/A",
          tags: ["Mechanical Engineering", "Chemical Engineering", "Metallurgical Engineering", "Technical Sales", "Pump Technology", "Entry Level"],
          shortDescription: "Applications Engineer role providing technical support for heavy-duty slurry pump sales, conducting site analysis, and delivering customer solutions.",
          fullDescription: "Pump and Abrasion Technologies seeks an Applications Engineer for technical sales support. Responsibilities include pump selection, system analysis, technical proposals, customer guidance, and site visits. Ideal for recent Mechanical, Chemical, or Metallurgical Engineering graduates. Salary range R216,000-R240,000 per annum with travel opportunities."
          },
          {
            id: "developer-internship-role-parvana-jhb",
            title: "Developer - Internship Role",
            company: "Parvana",
            location: "Johannesburg, Gauteng",
            type: "Permanent • Internship",
            duration: "Permanent",
            reportTo: "N/A",
            datePosted: "2023-03-28T00:00:00+02:00",
            closingDate: "N/A",
            applicationLink: "https://jobs.parvana.co.uk/jobs/Careers/448937000037661610/Developer---Internship-Role-JHB-?source=CareerSite",
            reference: "J100942",
            tags: ["Software Development", "IT & Technology", "Internship", "4GL", "Unix", "Agile"],
            shortDescription: "Developer internship role with comprehensive training program, perfect for recent graduates looking to start their career in software development.",
            fullDescription: "Parvana seeks a Developer for an internship role with extensive training program lasting over 4 months. The position involves research and development, coding in 4GL on Unix platform, and working with Agile/Scrum methodology. Ideal for candidates with completed 3-year Diploma or Degree in Computer Science, offering flexible hours and continuous learning opportunities."
            },
            {
              id: "graduate-software-development-programme-parvana-2024",
              title: "Graduate Software Development Programme",
              company: "Parvana",
              location: "Johannesburg, Gauteng and Cape Town, Western Cape",
              type: "Contract • Graduate Programme",
              duration: "Not Specified",
              reportTo: "N/A",
              datePosted: "2024-11-29T00:00:00+02:00",
              closingDate: "N/A",
              applicationLink: "https://jobs.parvana.co.uk/jobs/Careers/448937000089213609/Graduate-Software-Development-Programme-CPT-JHB-?source=CareerSite",
              reference: "J106791",
              tags: ["Software Development", "IT & Technology", "Graduate Programme", "4GL", "Unix", "Agile", "Financial Services"],
              shortDescription: "Graduate Software Development Programme offering structured training and on-the-job learning in financial services solutions using 4GL on Unix platform.",
              fullDescription: "Parvana's client seeks graduates for a Software Development Programme with over 4 months of formal training and structured learning. The role involves research and development, coding in 4GL on Unix platform, and working with Agile/Scrum methodology. Ideal for recent Computer Science graduates passionate about learning and growing in a collaborative financial services environment."
              },
              {
                id: "graduate-internship-programme-25-engineers-free-state-premier",
                title: "Graduate Internship Programme - 25 Engineers",
                company: "Office of the Premier, Free State Province",
                location: "Various Districts, Free State",
                type: "Internship • Work Integrated Learning",
                duration: "24 Months",
                reportTo: "District Coordinators",
                datePosted: "2025-09-30T00:00:00+02:00",
                closingDate: "2025-10-10",
                applicationLink: "mailto:linie.nkemele@fryremier.gov.za",
                reference: "N/A",
                tags: ["Civil Engineering", "Environmental Engineering", "Quantity Surveying", "Urban Planning", "Graduate Programme", "Public Service"],
                shortDescription: "25 engineering graduate positions across 5 district municipalities in Free State for 24-month internship programme with on-the-job development training.",
                fullDescription: `
                The Office of the Premier, Free State Province invites applications for 25 engineering graduates to participate in a 24-month Graduate Internship Programme and Work Integrated Learning.
                
                Successful candidates will be placed across 5 District Municipalities (Motheo, Thabo Mofutsanyana, Lejweleputswa, Fezile Dabi, and Xhariep) and will undergo comprehensive on-the-job development training in technical, professional, public service, and life skills.
                
                The programme aims to enhance employability of unemployed graduates while improving service delivery in district municipalities.
                
                Required qualifications include National Diploma/Degree/B-Tech in:
                • Civil Engineering
                • Civil Engineering Project Management
                • Hydrology and Water Resources Engineering
                • Environmental Water Management
                • Quantity Surveying
                • Urban and Rural Planning
                • Engineering Studies
                
                A stipend will be paid according to the revised Directive on Developmental Programme in the Public Service.
                
                Applications must include updated CV with certified copies of qualifications, ID, and academic transcripts submitted to respective district coordinators.
                
                Email applications to: linie.nkemele@fryremier.gov.za
                }, { id: "electronics-instrumentation-technician-petrogistix-saudi-arabia", title: "Electronics and Instrumentation Technician", company: "Petroleum & Energy Logistics & Services Co. (Petrogistix)", location: "Khobar City, Saudi Arabia", type: "Full-time • Permanent", duration: "Permanent", reportTo: "Technical Manager", datePosted: "2025-09-30T00:00:00+02:00", closingDate: "2025-10-25", applicationLink: "mailto:jobs@petrogistix.com", reference: "N/A", tags: ["Electrical Engineering", "Electronics", "Instrumentation", "Oil & Gas", "International"], shortDescription: "Electronics and Instrumentation Technician role at Petrogistix in Saudi Arabia, focusing on installation, maintenance and repair of electronic systems in Oil & Gas equipment.", fullDescription:
                Petrogistix, a 100% Saudi company headquartered in Khobar providing innovative services to regional Oil & Gas operators, seeks an Electronics and Instrumentation Technician.
                
                Key Responsibilities:
                • Install, maintain, and repair electronic systems and instrumentation in PGX equipment
                • Test, calibrate, and troubleshoot sensors and control devices
                • Perform routine inspections and preventive maintenance
                • Ensure compliance with safety protocols and accurate instrument readings
                • Assist in system upgrades to improve efficiency and reliability
                
                Required Skills and Qualifications:
                • 0-3 years experience with calibration, maintenance and installation of electronic instruments
                • Knowledge of PLC systems and basic programming
                • Ability to read wiring diagrams, P&IDs, and schematics
                • Proficiency with diagnostic tools like multimeters
                • Understanding of analog and digital signals
                • High School or Diploma qualification
                • Strong problem-solving, communication, and teamwork skills
                • Basic computer skills for data logging and documentation
                • Basic English language proficiency
                
                Applications accepted until 25 October 2025 via email with job title in subject line.
                
                Email applications to: jobs@petrogistix.com
                }, { id: "junior-project-engineer-renewable-energy-cape-town", title: "Junior Project Engineer - Renewable Energy", company: "Leading Independent Power Producer (IPP)", location: "Cape Town, Western Cape", type: "Full-time • Permanent", duration: "Permanent", reportTo: "Project Manager", datePosted: "2025-09-30T00:00:00+02:00", closingDate: "N/A", applicationLink: "mailto:engineering.vacancy@stand-outstaffing.co.za", reference: "N/A", tags: ["Electrical Engineering", "Civil Engineering", "Renewable Energy", "Project Engineering", "Energy Sector"], shortDescription: "Junior Project Engineer position in Cape Town for renewable energy projects, ideal for recent graduates or new professionals passionate about sustainable energy.", fullDescription:
                A leading Independent Power Producer (IPP) in the renewable energy sector is seeking a Junior Project Engineer to join their team in Cape Town.
                
                This position offers an excellent opportunity for new professionals or recent graduates with a passion for renewable energy to gain valuable experience in the growing sustainable energy sector.
                
                Key Responsibilities:
                • Participate in engineering design and development
                • Develop and compile tenders and project documentation
                • Provide contractor oversight and quality assurance
                • Serve as technical interface between clients, contractors and management
                • Support time and budget objectives for projects
                • Ensure compliance with engineering standards and regulations
                
                Role Requirements:
                • BSc Electrical Engineering or BSc Civil Engineering
                • BTech Electrical Engineering or BTech Civil Engineering
                • Minimum 1 year relevant experience
                • Willingness to occasionally travel for short-term assignments
                • Ability to work both individually and in teams
                • Excellent written and verbal communication skills
                • Strong problem-solving and analytical abilities
                
                Email applications to: engineering.vacancy@stand-outstaffing.co.za
                `
                }
  ];